version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__SupabaseConnection=Host=db;Database=finance;Username=postgres;Password=postgrespw
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: finance
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: